(function (global) {
    const uiStrings = {
        classSelectionTitle: "🧠 Тест з обчислювального мислення для дітей",
        classSelectionSubtitle: "Обери свій рівень, щоб почати гру! 👇",
        grades: {
            "2": "Початковий рівень (2 кл.) 🐣",
            "3": "Середній рівень (3 кл.) 🦁",
            "4": "Просунутий рівень (4 кл.) 🚀"
        },
        shortGrades: {
            "2": "Початковий",
            "3": "Середній",
            "4": "Просунутий"
        },
        next: "Далі 🚀",
        finish: "Завершити тест! 🏆",
        finishEarly: "Завершити достроково",
        reviewSkipped: "Перейти до пропущених ➡️",
        skip: "Пропустити 🤔",
        clearChoice: "Очистити вибір",
        reviewButton: "Переглянути пропущені питання",
        reviewTitle: "Перегляд питань",
        reviewDescription: "Натисни на номер, щоб повернутися до питання.",
        reviewClose: "Закрити",
        finishModalTitle: "Завершити тест достроково?",
        finishModalDescription: "Поточні відповіді будуть зараховані, а пропущені питання залишаться без відповіді.",
        finishModalCancel: "Скасувати",
        finishModalConfirm: "Завершити",
        resultLabel: "Твій результат:",
        resultAnalysis: "Аналіз відповідей:",
        resultAdultSummary: "Для дорослих: що вже добре і що потренувати",
        adultSummaryStrong: "У цій спробі дитина впевнено впоралася з більшістю тем.",
        adultSummaryMixed: "У цій спробі є і впевнені відповіді, і теми для додаткової практики.",
        adultSummaryNeedsSupport: "У цій спробі видно теми, які варто спокійно допрацювати разом.",
        adultSummaryPreliminary: "У цій спробі є лише попередні сигнали: для точніших висновків потрібно більше ніж одне завдання на тему.",
        adultSummaryFocusLabel: "Що потренувати далі:",
        adultSummaryStrengthLabel: "Що вже виходить добре:",
        adultSummaryObservedLabel: "Де поки що замало даних:",
        resultConcepts: "💡 Аналітика за концепціями: детальніше",
        resultConceptNote: "Висновок зроблено лише за цією спробою; одна відповідь по темі ще не дає надійного висновку.",
        resultNeedsPractice: "Що варто повторити: детальніше",
        resultAllClear: "У цій спробі тут без помилок.",
        resultConceptEmpty: "Для висновків у цій спробі ще замало даних.",
        conceptStatusStrong: "Впевнено",
        conceptStatusPartial: "Частково впевнено",
        conceptStatusNeedsPractice: "Потрібна практика",
        conceptStatusPreliminary: "Попередній сигнал",
        conceptCorrectnessLabel: "Правильних відповідей:",
        conceptPracticeSummaryLabel: "Що потренувати:",
        conceptEvidenceLabel: "Надійність висновку:",
        conceptPracticeHintMissed: "\u0423 \u0446\u0456\u0439 \u0441\u043f\u0440\u043e\u0431\u0456 \u0434\u043e \u0446\u0456\u0454\u0457 \u0442\u0435\u043c\u0438 \u0432\u0430\u0440\u0442\u043e \u043f\u043e\u0432\u0435\u0440\u043d\u0443\u0442\u0438\u0441\u044f \u0449\u0435 \u0440\u0430\u0437.",
        conceptPracticeHintPartial: "\u0404 \u043f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u0456 \u043a\u0440\u043e\u043a\u0438, \u0430\u043b\u0435 \u0449\u0435 \u043a\u043e\u0440\u0438\u0441\u043d\u043e \u0442\u0440\u043e\u0445\u0438 \u043f\u043e\u0442\u0440\u0435\u043d\u0443\u0432\u0430\u0442\u0438\u0441\u044f.",
        conceptPracticeHintPreliminary: "Тут поки що був лише один сигнал, тому краще дати ще 1-2 схожі завдання перед висновком.",
        conceptEvidenceStrong: "Достатньо даних у цій спробі",
        conceptEvidencePreliminary: "Поки що лише одне завдання на тему",
        conceptEncounteredLabel: "Теми з цієї спроби:",
        conceptObservedLabel: "Попередні сигнали:",
        shareResults: "Поділитися результатом",
        shareNativeTitle: "Результат тесту з обчислювального мислення",
        shareSuccessNotice: "Посилання на результат скопійовано. Можна надіслати в месенджер або зберегти в закладках.",
        shareUnavailableNotice: "На цьому пристрої не вдалося відкрити меню «Поділитися». Тому посилання скопійовано в буфер обміну.",
        shareErrorNotice: "Не вдалося сформувати посилання для поширення. Спробуй ще раз.",
        sharedResultModeLabel: "Відкрито результат із посилання",
        sharedResultDetailsNote: "У спільному посиланні збережено лише підсумок: без персональних даних і без детальних відповідей на кожне питання.",
        restart: "Почати знову! 🔄",
        levelLabel: "Рівень:",
        questionProgress: "Завдання",
        scorePerfect: "Суперрезультат у цій спробі! 🚀",
        scoreGreat: "Дуже гарна спроба! Ще трохи практики - і буде ще краще. 🌟",
        scoreOkay: "Хороший старт! У наступній спробі вийде ще впевненіше. 💪",
        scoreNeedsWork: "Це лише етап навчання: спокійно потренуємося - і буде прогрес. 💡",
        statusCorrect: "✅ Правильно!",
        statusIncorrect: "❌ Помилка!",
        statusSkipped: "⚠️ Пропущено",
        yourAnswer: "Твоя відповідь:",
        correctAnswer: "Правильна відповідь:",
        explanation: "💡 Пояснення:",
        concept: "Концепція:",
        skippedNotice: "Питання пропущено. До нього можна повернутися пізніше.",
        clearedNotice: "Вибір очищено. Питання стало пропущеним.",
        endReviewNotice: "Кінець тесту. Повертаємося до пропущеного питання.",
        finalSkippedNotice: "Останнє питання пропущено. Переходимо до першого пропущеного.",
        skipToResultsNotice: "\u041f\u0438\u0442\u0430\u043d\u043d\u044f \u043f\u0440\u043e\u043f\u0443\u0449\u0435\u043d\u043e. \u041f\u0435\u0440\u0435\u0445\u043e\u0434\u0438\u043c\u043e \u0434\u043e \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u0456\u0432.",
        completedLoopNotice: "Тест майже завершено. Переходимо до пропущених питань.",
        answerRequiredNotice: "Будь ласка, обери варіант відповіді, щоб продовжити.",
        stateRestoredNotice: "Незавершену спробу відновлено.",
        stateResetNotice: "\u041f\u043e\u043f\u0435\u0440\u0435\u0434\u043d\u044e \u0441\u043f\u0440\u043e\u0431\u0443 \u043e\u0447\u0438\u0449\u0435\u043d\u043e.",
        finishEarlyNotice: "Тест завершено достроково. Показую результат.",
        liveRegionDefault: "\u0413\u043e\u0442\u043e\u0432\u043e \u0434\u043e \u043f\u0440\u043e\u0445\u043e\u0434\u0436\u0435\u043d\u043d\u044f \u0442\u0435\u0441\u0442\u0443."
    };

    global.uiStrings = uiStrings;

    if (typeof module !== "undefined" && module.exports) {
        module.exports = uiStrings;
    }
})(typeof window !== "undefined" ? window : globalThis);
