export const EXAMPLES = [

  {
    id: 'ex-linear',
    title: 'Ранок школяра',
    subtitle: 'Лінійний алгоритм - дії йдуть одна за одною',
    icon: 'fa-sun',
    color: '#f59e0b',
    bg: 'bg-amber-50',
    border: 'border-amber-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'process', text: 'Прокинутися' },
      { id: 'n3', type: 'process', text: 'Вмитися та почистити зуби' },
      { id: 'n4', type: 'process', text: 'Поснідати' },
      { id: 'n5', type: 'process', text: 'Вдягнутися' },
      { id: 'n6', type: 'process', text: 'Вийти з дому' },
      { id: 'n7', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n4', label: null },
      { from: 'n4', to: 'n5', label: null },
      { from: 'n5', to: 'n6', label: null },
      { from: 'n6', to: 'n7', label: null },
    ],
    root: 'n1',
    comments: {},
    commentPos: {},
  },

  {
    id: 'ex-branch',
    title: 'Чи брати парасольку?',
    subtitle: 'Розгалуження - різні дії залежно від умови',
    icon: 'fa-umbrella',
    color: '#0ea5e9',
    bg: 'bg-sky-50',
    border: 'border-sky-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'process', text: 'Подивитися у вікно' },
      { id: 'n3', type: 'decision', text: 'Іде дощ?' },
      { id: 'n4', type: 'process', text: 'Взяти парасольку' },
      { id: 'n5', type: 'process', text: 'Залишити парасольку вдома' },
      { id: 'n6', type: 'end', text: 'Кінець' },
      { id: 'n7', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n4', label: 'yes' },
      { from: 'n3', to: 'n5', label: 'no' },
      { from: 'n4', to: 'n6', label: null },
      { from: 'n5', to: 'n7', label: null },
    ],
    root: 'n1',
    comments: {
      n3: 'Тут є вибір: якщо дощ, діємо так, якщо ні - інакше.',
    },
    commentPos: {
      n3: { x: 24, y: -10 },
    },
  },

  {
    id: 'ex-if-only',
    title: 'Прибирання кімнати',
    subtitle: 'Неповна форма - дія виконується лише за умови',
    icon: 'fa-broom',
    color: '#f59e0b',
    bg: 'bg-amber-50',
    border: 'border-amber-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'decision', text: 'Кімната брудна?' },
      { id: 'n3', type: 'process', text: 'Прибрати кімнату' },
      { id: 'n4', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: 'yes' },
      { from: 'n2', to: 'n4', label: 'no' },
      { from: 'n3', to: 'n4', label: null },
    ],
    root: 'n1',
    comments: {
      n2: 'Коли відповідь «Ні», нічого не робимо і одразу завершуємо.',
    },
    commentPos: {
      n2: { x: 36, y: -6 },
    },
  },

  {
    id: 'ex-merge',
    title: 'Вибір транспорту',
    subtitle: 'Розгалуження зі сходженням - гілки об\'єднуються',
    icon: 'fa-bus',
    color: '#22c55e',
    bg: 'bg-green-50',
    border: 'border-green-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'decision', text: 'Є квиток на автобус?' },
      { id: 'n3', type: 'process', text: 'Сісти в автобус' },
      { id: 'n4', type: 'process', text: 'Іти пішки' },
      { id: 'n5', type: 'process', text: 'Дістатися до школи' },
      { id: 'n6', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: 'yes' },
      { from: 'n2', to: 'n4', label: 'no' },
      { from: 'n3', to: 'n5', label: null },
      { from: 'n4', to: 'n5', label: null },
      { from: 'n5', to: 'n6', label: null },
    ],
    root: 'n1',
    comments: {
      n5: 'Після двох різних шляхів алгоритм знову йде разом.',
    },
    commentPos: {
      n5: { x: 42, y: 12 },
    },
  },

  {
    id: 'ex-io',
    title: 'Перевірка паролю',
    subtitle: 'Ввід даних, перевірка умови та вивід результату',
    icon: 'fa-lock',
    color: '#a855f7',
    bg: 'bg-violet-50',
    border: 'border-violet-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'input-output', text: 'Ввести пароль' },
      { id: 'n3', type: 'decision', text: 'Пароль правильний?' },
      { id: 'n4', type: 'input-output', text: 'Показати: «Ласкаво просимо!»' },
      { id: 'n5', type: 'input-output', text: 'Показати: «Помилка! Спробуй ще раз»' },
      { id: 'n6', type: 'end', text: 'Кінець' },
      { id: 'n7', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n4', label: 'yes' },
      { from: 'n3', to: 'n5', label: 'no' },
      { from: 'n4', to: 'n6', label: null },
      { from: 'n5', to: 'n7', label: null },
    ],
    root: 'n1',
    comments: {
      n2: 'Тут ми вводимо дані від користувача.',
      n4: 'Тут показуємо відповідь на екрані.',
    },
    commentPos: {
      n2: { x: 24, y: -12 },
      n4: { x: 24, y: -8 },
    },
  },

  {
    id: 'ex-complex',
    title: 'Купівля морозива',
    subtitle: 'Складніший алгоритм з кількома умовами',
    icon: 'fa-ice-cream',
    color: '#f43f5e',
    bg: 'bg-rose-50',
    border: 'border-rose-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'input-output', text: 'Порахувати гроші' },
      { id: 'n3', type: 'decision', text: 'Вистачає грошей?' },
      { id: 'n4', type: 'process', text: 'Підійти до кіоску' },
      { id: 'n5', type: 'process', text: 'Повернутись додому' },
      { id: 'n6', type: 'decision', text: 'Є шоколадне?' },
      { id: 'n7', type: 'process', text: 'Купити шоколадне' },
      { id: 'n8', type: 'process', text: 'Купити ванільне' },
      { id: 'n9', type: 'process', text: 'З\'їсти морозиво' },
      { id: 'n10', type: 'end', text: 'Кінець' },
      { id: 'n11', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n4', label: 'yes' },
      { from: 'n3', to: 'n5', label: 'no' },
      { from: 'n5', to: 'n11', label: null },
      { from: 'n4', to: 'n6', label: null },
      { from: 'n6', to: 'n7', label: 'yes' },
      { from: 'n6', to: 'n8', label: 'no' },
      { from: 'n7', to: 'n9', label: null },
      { from: 'n8', to: 'n9', label: null },
      { from: 'n9', to: 'n10', label: null },
    ],
    root: 'n1',
    comments: {
      n3: 'Спочатку з\'ясовуємо, чи вистачає грошей.',
      n6: 'Друга перевірка працює тільки після відповіді «Так» вище.',
      n9: 'Обидва варіанти приводять до одного результату.',
    },
    commentPos: {
      n3: { x: 28, y: -12 },
      n6: { x: 18, y: -8 },
      n9: { x: 22, y: 20 },
    },
  },

  {
    id: 'ex-while',
    title: 'Рахуємо до 5',
    subtitle: 'Цикл while - умова перевіряється перед кожним повторенням',
    icon: 'fa-rotate',
    color: '#0ea5e9',
    bg: 'bg-sky-50',
    border: 'border-sky-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'process', text: 'i = 1' },
      { id: 'n3', type: 'decision', text: 'i ? 5?' },
      { id: 'n4', type: 'input-output', text: 'Вивести i' },
      { id: 'n5', type: 'process', text: 'i = i + 1' },
      { id: 'n6', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n4', label: 'yes' },
      { from: 'n4', to: 'n5', label: null },
      { from: 'n5', to: 'n3', label: null },
      { from: 'n3', to: 'n6', label: 'no' },
    ],
    root: 'n1',
    comments: {
      n2: 'Спочатку задаємо лічильник.',
      n3: 'Поки умова істинна, цикл повторюється.',
      n5: 'Після кожного кола збільшуємо лічильник.',
    },
    commentPos: {
      n2: { x: 24, y: -12 },
      n3: { x: 18, y: 0 },
      n5: { x: 22, y: 16 },
    },
  },

  {
    id: 'ex-dowhile',
    title: 'Вгадай число',
    subtitle: 'Цикл do-while - умова перевіряється після кожної спроби',
    icon: 'fa-dice',
    color: '#a855f7',
    bg: 'bg-violet-50',
    border: 'border-violet-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'input-output', text: 'Ввести число' },
      { id: 'n3', type: 'decision', text: 'Число = 7?' },
      { id: 'n4', type: 'input-output', text: 'Показати: «Не вгадав!»' },
      { id: 'n5', type: 'input-output', text: 'Показати: «Ти вгадав!»' },
      { id: 'n6', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n5', label: 'yes' },
      { from: 'n3', to: 'n4', label: 'no' },
      { from: 'n4', to: 'n2', label: null },
      { from: 'n5', to: 'n6', label: null },
    ],
    root: 'n1',
    comments: {
      n2: 'Спочатку виконуємо дію, а перевірка буде потім.',
      n3: 'Тут вирішуємо: зупинитися чи повторити ще раз.',
    },
    commentPos: {
      n2: { x: 34, y: -14 },
      n3: { x: 22, y: 8 },
    },
  },

  {
    id: 'ex-for',
    title: 'Таблиця множення на 2',
    subtitle: 'Цикл for - точна кількість повторень',
    icon: 'fa-table',
    color: '#22c55e',
    bg: 'bg-green-50',
    border: 'border-green-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'process', text: 'i = 1' },
      { id: 'n3', type: 'decision', text: 'i ? 10?' },
      { id: 'n4', type: 'input-output', text: 'Вивести 2 ? i' },
      { id: 'n5', type: 'process', text: 'i = i + 1' },
      { id: 'n6', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n4', label: 'yes' },
      { from: 'n4', to: 'n5', label: null },
      { from: 'n5', to: 'n3', label: null },
      { from: 'n3', to: 'n6', label: 'no' },
    ],
    root: 'n1',
    comments: {
      n2: 'Задаємо число, з якого почнемо.',
      n3: 'Перевіряємо, чи треба повторювати далі.',
      n5: 'Після кожного кроку збільшуємо лічильник.',
    },
    commentPos: {
      n2: { x: 24, y: -14 },
      n3: { x: 24, y: 0 },
      n5: { x: 22, y: 16 },
    },
  },

  {
    id: 'ex-sub',
    title: 'Знайти суму масиву',
    subtitle: 'Виклик підпрограми для обчислення суми',
    icon: 'fa-sigma',
    color: '#0f766e',
    bg: 'bg-teal-50',
    border: 'border-teal-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'input-output', text: 'Ввести масив A' },
      { id: 'n3', type: 'subroutine', text: 'Сума(A)' },
      { id: 'n4', type: 'input-output', text: 'Вивести результат' },
      { id: 'n5', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n4', label: null },
      { from: 'n4', to: 'n5', label: null },
    ],
    root: 'n1',
    comments: {
      n3: 'Підпрограма виконує частину роботи замість головної схеми.',
    },
    commentPos: {
      n3: { x: 28, y: -6 },
    },
  },

];

