export const EXAMPLES = [

  // --- 1. ЛІНІЙНИЙ АЛГОРИТМ ------------------------------------------------
  {
    id: 'ex-linear',
    title: 'Ранок школяра',
    subtitle: 'Лінійний алгоритм - дії йдуть одна за одною',
    icon: 'fa-sun',
    color: '#f59e0b',
    bg: 'bg-amber-50',
    border: 'border-amber-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'process', text: 'Прокинутися' },
      { id: 'n3', type: 'process', text: 'Вмитися та почистити зуби' },
      { id: 'n4', type: 'process', text: 'Поснідати' },
      { id: 'n5', type: 'process', text: 'Вдягнутися' },
      { id: 'n6', type: 'process', text: 'Вийти з дому' },
      { id: 'n7', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n4', label: null },
      { from: 'n4', to: 'n5', label: null },
      { from: 'n5', to: 'n6', label: null },
      { from: 'n6', to: 'n7', label: null },
    ],
    root: 'n1',
    comments: {},
  },

  // --- 2. ПОВНА ФОРМА РОЗГАЛУЖЕННЯ (if/else) -------------------------------
  {
    id: 'ex-branch',
    title: 'Чи брати парасольку?',
    subtitle: 'Розгалуження - різні дії залежно від умови',
    icon: 'fa-umbrella',
    color: '#0ea5e9',
    bg: 'bg-sky-50',
    border: 'border-sky-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'process', text: 'Подивитися у вікно' },
      { id: 'n3', type: 'decision', text: 'Іде дощ?' },
      { id: 'n4', type: 'process', text: 'Взяти парасольку' },
      { id: 'n5', type: 'process', text: 'Залишити парасольку вдома' },
      { id: 'n6', type: 'end', text: 'Кінець' },
      { id: 'n7', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n4', label: 'yes' },
      { from: 'n3', to: 'n5', label: 'no' },
      { from: 'n4', to: 'n6', label: null },
      { from: 'n5', to: 'n7', label: null },
    ],
    root: 'n1',
    comments: {
      n3: 'Тут алгоритм перевіряє умову і ділиться на два різних шляхи',
    },
  },

  // --- 3. НЕПОВНА ФОРМА РОЗГАЛУЖЕННЯ (if без else) -------------------------
  {
    id: 'ex-if-only',
    title: 'Прибирання кімнати',
    subtitle: 'Неповна форма - дія виконується лише за умови',
    icon: 'fa-broom',
    color: '#f59e0b',
    bg: 'bg-amber-50',
    border: 'border-amber-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'decision', text: 'Кімната брудна?' },
      { id: 'n3', type: 'process', text: 'Прибрати кімнату' },
      { id: 'n4', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: 'yes' },
      { from: 'n2', to: 'n4', label: 'no' },
      { from: 'n3', to: 'n4', label: null },
    ],
    root: 'n1',
    comments: {
      n2: 'Якщо умова «Ні» - дія пропускається і одразу переходимо до кінця',
    },
  },

  // --- 4. РОЗГАЛУЖЕННЯ ЗІ ЗЛИТТЯМ ГІЛОК ------------------------------------
  {
    id: 'ex-merge',
    title: 'Вибір транспорту',
    subtitle: 'Розгалуження зі сходженням - гілки об\'єднуються',
    icon: 'fa-bus',
    color: '#22c55e',
    bg: 'bg-green-50',
    border: 'border-green-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'decision', text: 'Є квиток на автобус?' },
      { id: 'n3', type: 'process', text: 'Сісти в автобус' },
      { id: 'n4', type: 'process', text: 'Іти пішки' },
      { id: 'n5', type: 'process', text: 'Дістатися до школи' },
      { id: 'n6', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: 'yes' },
      { from: 'n2', to: 'n4', label: 'no' },
      { from: 'n3', to: 'n5', label: null },
      { from: 'n4', to: 'n5', label: null },
      { from: 'n5', to: 'n6', label: null },
    ],
    root: 'n1',
    comments: {
      n5: 'Обидві гілки з\'єднались - далі алгоритм іде одним спільним шляхом',
    },
  },

  // --- 5. ВВІД / ВИВІД + РОЗГАЛУЖЕННЯ -------------------------------------
  {
    id: 'ex-io',
    title: 'Перевірка паролю',
    subtitle: 'Ввід даних, перевірка умови та вивід результату',
    icon: 'fa-lock',
    color: '#a855f7',
    bg: 'bg-violet-50',
    border: 'border-violet-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'input-output', text: 'Ввести пароль' },
      { id: 'n3', type: 'decision', text: 'Пароль правильний?' },
      { id: 'n4', type: 'input-output', text: 'Показати: «Ласкаво просимо!»' },
      { id: 'n5', type: 'input-output', text: 'Показати: «Помилка! Спробуй ще раз»' },
      { id: 'n6', type: 'end', text: 'Кінець' },
      { id: 'n7', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n4', label: 'yes' },
      { from: 'n3', to: 'n5', label: 'no' },
      { from: 'n4', to: 'n6', label: null },
      { from: 'n5', to: 'n7', label: null },
    ],
    root: 'n1',
    comments: {
      n2: 'Паралелограм - блок введення або виведення даних',
      n4: 'Вивід результату залежить від умови вище',
    },
  },

  // --- 6. ВКЛАДЕНІ УМОВИ (кілька рішень) -----------------------------------
  {
    id: 'ex-complex',
    title: 'Купівля морозива',
    subtitle: 'Складніший алгоритм з кількома умовами',
    icon: 'fa-ice-cream',
    color: '#f43f5e',
    bg: 'bg-rose-50',
    border: 'border-rose-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'input-output', text: 'Порахувати гроші' },
      { id: 'n3', type: 'decision', text: 'Вистачає грошей?' },
      { id: 'n4', type: 'process', text: 'Підійти до кіоску' },
      { id: 'n5', type: 'process', text: 'Повернутись додому' },
      { id: 'n6', type: 'decision', text: 'Є шоколадне?' },
      { id: 'n7', type: 'process', text: 'Купити шоколадне' },
      { id: 'n8', type: 'process', text: 'Купити ванільне' },
      { id: 'n9', type: 'process', text: 'З\'їсти морозиво' },
      { id: 'n10', type: 'end', text: 'Кінець' },
      { id: 'n11', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n4', label: 'yes' },
      { from: 'n3', to: 'n5', label: 'no' },
      { from: 'n5', to: 'n11', label: null },
      { from: 'n4', to: 'n6', label: null },
      { from: 'n6', to: 'n7', label: 'yes' },
      { from: 'n6', to: 'n8', label: 'no' },
      { from: 'n7', to: 'n9', label: null },
      { from: 'n8', to: 'n9', label: null },
      { from: 'n9', to: 'n10', label: null },
    ],
    root: 'n1',
    comments: {
      n3: 'Умова 1: перевіряємо, чи вистачає грошей',
      n6: 'Умова 2: вкладена - перевіряємо смак всередині першої гілки',
      n9: 'Гілки об\'єднались: обидва шляхи ведуть до одного блоку',
    },
  },

  // --- 7. ЦИКЛ З ПЕРЕДУМОВОЮ (while) ---------------------------------------
  {
    id: 'ex-while',
    title: 'Рахуємо до 5',
    subtitle: 'Цикл while - умова перевіряється перед кожним повторенням',
    icon: 'fa-rotate',
    color: '#0ea5e9',
    bg: 'bg-sky-50',
    border: 'border-sky-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'process', text: 'i = 1' },
      { id: 'n3', type: 'decision', text: 'i ≤ 5?' },
      { id: 'n4', type: 'input-output', text: 'Вивести i' },
      { id: 'n5', type: 'process', text: 'i = i + 1' },
      { id: 'n6', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n4', label: 'yes' },
      { from: 'n4', to: 'n5', label: null },
      { from: 'n5', to: 'n3', label: null },
      { from: 'n3', to: 'n6', label: 'no' },
    ],
    root: 'n1',
    comments: {
      n2: 'Ініціалізація: встановлюємо початкове значення лічильника',
      n3: 'Умова while: перевіряється ПЕРЕД кожним повторенням',
      n5: 'Зміна лічильника - без цього цикл ніколи не зупиниться!',
    },
  },

  // --- 8. ЦИКЛ З ПОСТУМОВОЮ (do-while / repeat-until) ----------------------
  {
    id: 'ex-dowhile',
    title: 'Вгадай число',
    subtitle: 'Цикл do-while - умова перевіряється після кожної спроби',
    icon: 'fa-dice',
    color: '#a855f7',
    bg: 'bg-violet-50',
    border: 'border-violet-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'input-output', text: 'Ввести число' },
      { id: 'n3', type: 'decision', text: 'Число = 7?' },
      { id: 'n4', type: 'input-output', text: 'Показати: «Не вгадав!»' },
      { id: 'n5', type: 'input-output', text: 'Показати: «Ти вгадав!»' },
      { id: 'n6', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n5', label: 'yes' },
      { from: 'n3', to: 'n4', label: 'no' },
      { from: 'n4', to: 'n2', label: null },
      { from: 'n5', to: 'n6', label: null },
    ],
    root: 'n1',
    comments: {
      n2: 'Тіло циклу виконується хоча б один раз - ще до перевірки умови',
      n3: 'Умова - тільки тут: ПІСЛЯ тіла. Ось чим do-while відрізняється від while',
    },
  },

  // --- 9. ЦИКЛ З ЛІЧИЛЬНИКОМ (for) -----------------------------------------
  {
    id: 'ex-for',
    title: 'Таблиця множення на 2',
    subtitle: 'Цикл for - точна кількість повторень',
    icon: 'fa-table',
    color: '#22c55e',
    bg: 'bg-green-50',
    border: 'border-green-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'process', text: 'i = 1' },
      { id: 'n3', type: 'decision', text: 'i ≤ 10?' },
      { id: 'n4', type: 'input-output', text: 'Вивести 2 × i' },
      { id: 'n5', type: 'process', text: 'i = i + 1' },
      { id: 'n6', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n4', label: 'yes' },
      { from: 'n4', to: 'n5', label: null },
      { from: 'n5', to: 'n3', label: null },
      { from: 'n3', to: 'n6', label: 'no' },
    ],
    root: 'n1',
    comments: {
      n2: 'for, крок 1: початкове значення. Виконується один раз на початку',
      n3: 'for, крок 2: умова. Перевіряється перед кожним повторенням',
      n5: 'for, крок 3: зміна лічильника. Виконується після тіла циклу',
    },
  },

  // --- 10. ДОПОМІЖНИЙ АЛГОРИТМ (підпрограма) -------------------------------
  {
    id: 'ex-sub',
    title: 'Знайти суму масиву',
    subtitle: 'Виклик підпрограми для обчислення суми',
    icon: 'fa-sigma',
    color: '#0f766e',
    bg: 'bg-teal-50',
    border: 'border-teal-200',
    nodes: [
      { id: 'n1', type: 'start', text: 'Початок' },
      { id: 'n2', type: 'input-output', text: 'Ввести масив A' },
      { id: 'n3', type: 'subroutine', text: 'Сума(A)' },
      { id: 'n4', type: 'input-output', text: 'Вивести результат' },
      { id: 'n5', type: 'end', text: 'Кінець' },
    ],
    edges: [
      { from: 'n1', to: 'n2', label: null },
      { from: 'n2', to: 'n3', label: null },
      { from: 'n3', to: 'n4', label: null },
      { from: 'n4', to: 'n5', label: null },
    ],
    root: 'n1',
    comments: {
      n3: 'Підпрограма виконує окреме завдання і повертає результат у головний алгоритм',
    },
  },

];
