window.UI_STRINGS = {
    app: {
        documentTitle: 'Місія: Порятунок Сервера | Інтерактивний тест з інформатики',
        metaDescription: 'Навчальна гра: Місія Порятунок Сервера',
        themeColor: '#0d1117',
        skipLink: 'Перейти до основного вмісту',
        systemStatus: 'Стан системи',
        resetGameTitle: 'Скинути гру',
        resetGameAria: 'Скинути прогрес',
        levelLabel: 'Рівень:',
        robotLabel: 'ШІ Біп-Боп:',
        skipDialogue: 'Пропустити текст',
        missionTitle: 'МІСІЯ:<br>Порятунок Сервера',
        introParagraphOne: '<span class="text-red-400 font-bold">УВАГА!</span> У школі раптово вимкнули світло — шкільний сервер з електронним журналом <strong>перестав працювати</strong>.<br><br>Шкільний ШІ-помічник <strong>Біп-Боп</strong> також втратив частину даних і забув, як повернути сервер до робочого стану. Робота з оцінками та домашніми завданнями опинилась під загрозою.',
        introParagraphTwo: 'Системний адміністратор у відпустці (у його кішки народилися кошенята 🐱), тому <strong>лише ти можеш допомогти</strong> відновити сервер.',
        timerToggle: 'Увімкнути таймер (45 секунд на запитання)',
        timerHelp: 'За 20 секунд до кінця з\'явиться можливість додати ще 20 секунд.',
        startButton: '<i class="fas fa-power-off mr-2"></i> ВІДНОВИТИ СИСТЕМУ',
        endTitleVictory: 'МІСІЮ ВИКОНАНО!',
        resultLabel: 'Результат',
        finalHealthLabel: 'Здоров’я сервера:',
        errorCountLabel: 'Помилок:',
        improvementLabel: 'Зони для покращення',
        perfectScore: '<i class="fas fa-check-circle"></i> Жодних помилок!',
        restartButton: '<i class="fas fa-redo mr-2"></i> Нова гра'
    },
    runtime: {
        gameStarted: 'Гру розпочато. Переходимо до першого запитання.',
        progressAnnouncement: 'Прогрес проходження',
        healthAnnouncement: 'Здоров’я сервера',
        resetConfirm: 'Скинути весь прогрес і почати гру заново?',
        resetCanceled: 'Скидання прогресу скасовано.',
        offlineNotice: 'Немає інтернету. Якщо сторінка вже відкрита, тест продовжить працювати локально.',
        onlineNotice: 'З’єднання з інтернетом відновлено.',
        serviceWorkerFailed: 'Офлайн-режим поки не вдалося підготувати. Гру можна продовжити онлайн.',
        timerWarningAlert: 'Залишилося 20 секунд. Можна додати ще 20 секунд.',
        timerExtended: 'Час подовжено на 20 секунд.',
        timerWarningTitle: 'Майже час',
        timerWarningText: 'Залишилося 20 секунд. За потреби можна додати ще 20 секунд для відповіді.',
        timerWarningButton: 'Додати 20 с <i class="fas fa-hourglass-half"></i>',
        timeoutAlert: 'Час вичерпано. Переходимо далі після повідомлення.',
        timeoutMessage: 'Час вичерпано! Систему пошкоджено.',
        checkpointPrefix: 'Контрольна точка.',
        questionPrefix: 'Запитання',
        ofLabel: 'з',
        dialogueShown: 'Текст показано повністю.',
        optionPrefix: 'Варіант',
        correctTitle: 'Правильно!',
        incorrectTitle: 'Неправильно',
        learningHint: 'Було кілька складних запитань поспіль. Тест продовжується, але варто уважно читати підказки.',
        nextButton: 'Далі <i class="fas fa-arrow-right"></i>',
        continueMission: 'Продовжити місію <i class="fas fa-arrow-right ml-2"></i>',
        keyboardHint: 'Порада: використовуй Tab або стрілки для переходу між варіантами, Enter або Пробіл для вибору.',
        victorySummary: '<strong class="text-green-400">Вітаємо!</strong> Ти успішно відновив сервер.',
        victoryAnnouncement: 'Місію виконано. Сервер відновлено.',
        failureTitle: 'СИСТЕМА ВПАЛА',
        failureSummary: '<strong class="text-red-400">Сервер критично пошкоджено!</strong> Спробуй ще раз.',
        studyNeededSummary: '<strong class="text-red-400">Навчальна тривога!</strong><br>Ти помилився(-лась) 3 рази поспіль. Схоже, матеріал залишився незрозумілим.<br>Радимо повторити відповідні теми з інформатики і спробувати ще раз!',
        endAnnouncement: 'Гру завершено. Можна почати нову спробу.'
    },
    offline: {
        title: 'Офлайн | Місія: Порятунок Сервера',
        heading: 'Зараз немає з’єднання з інтернетом',
        paragraphOne: 'Якщо цей тест уже відкривався раніше, частина матеріалів може бути доступна локально. Коли інтернет з’явиться знову, просто повернися до гри.',
        paragraphTwo: 'Що можна зробити зараз:',
        itemOne: 'Перевірити, чи підключений інтернет.',
        itemTwo: 'Повернутися на головну сторінку тесту.',
        itemThree: 'Спробувати ще раз через кілька хвилин.',
        returnLink: 'Головна сторінка тесту'
    }
};
